export { Enum, EnumOptions, EnumValueWrapper, EnumMetadata, EnumType } from '../utility/enum'
export { Color } from './fabric.color.enum'
export { FontSize } from './fabric.fontsize.enum'
export { FontWeight } from './fabric.fontweight.enum'
export { IconType } from './fabric.icontype.enum'
export { AnimationType, AnimationStyle, AnimationFactory } from './fabric.animationtype.enum'
