import {EnumMetadata, EnumValueWrapper, enhanceEnum} from '../utility/enum'

export enum ColorEnum {
  Unspecified,
  ThemeDarker,
  ThemeDark,
  ThemeDarkAlt,
  ThemePrimary,
  ThemeSecondary,
  ThemeTertiary,
  ThemeLight,
  ThemeLighter,
  ThemeLighterAlt,
  Black,
  NeutralDark,
  NeutralPrimary,
  NeutralSecondary,
  NeutralSecondaryAlt,
  NeutralTertiary,
  NeutralTertiaryAlt,
  NeutralLight,
  NeutralLighter,
  NeutralLighterAlt,
  White,
  Yellow,
  YellowLight,
  Orange,
  OrangeLight,
  OrangeLighter,
  RedDark,
  Red,
  MagentaLight,
  Magenta,
  MagentaDark,
  PurpleLight,
  Purple,
  PurpleDark,
  BlueLight,
  BlueMid,
  Blue,
  BlueDark,
  TealLight,
  Teal,
  TealDark,
  GreenLight,
  Green,
  GreenDark,
  Info,
  Success,
  Alert,
  Error
}

export declare type EnumMetadata<T> = EnumMetadata<T>;

export var Color = enhanceEnum(ColorEnum, new EnumMetadata<ColorEnum>(ColorEnum, 'Color'));
